const T=["Hello.","I'd like to book a tour.","I'd like to visit Japan.","I'd like to visit Thailand.","I'd prefer France.","Could you recommend a hotel?","Where would you like to travel?","What would you like to do there?","I'd like to go sightseeing.","I'd like to try local food.","I'd like to stay at a hotel.","I'd like to stay for three nights.","How much is the room per night?","It costs forty-five dollars.","It costs fifteen dollars.","I'd like a double room.","That sounds good.","I'd rather stay at a hotel.","Could you repeat that, please?","I want go Japan."];
const $=x=>document.getElementById(x), SR=window.SpeechRecognition||window.webkitSpeechRecognition;let i=0,R=[],choice=null,rec;
function draw(){$("sentence").textContent=T[i];$("count").textContent=`${i+1} / ${T.length}`;$("prog").value=i+1;$("transcript").textContent="—";$("note").value="";$("status").textContent="Ready";choice=null;$("next").disabled=true;document.querySelectorAll(".judge").forEach(b=>b.classList.remove("sel"))}
$("listen").onclick=()=>{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(T[i]);u.lang="en-US";u.rate=.9;speechSynthesis.speak(u)};
function hear(){if(!SR){$("status").textContent="Speech recognition is unavailable in this browser.";return}if(rec)try{rec.abort()}catch(e){}rec=new SR;rec.lang="en-US";rec.interimResults=true;rec.continuous=false;rec.maxAlternatives=3;let f="";rec.onstart=()=>$("status").textContent="Listening… Speak now.";rec.onresult=e=>{let q="";for(let k=e.resultIndex;k<e.results.length;k++){let s=e.results[k][0].transcript;e.results[k].isFinal?f+=s:q+=s}$("transcript").textContent=(f||q||"—").trim()};rec.onerror=e=>$("status").textContent=({"no-speech":"No speech detected. Try again.","not-allowed":"Microphone permission was blocked.","audio-capture":"No microphone was found.","network":"Speech service/network error."}[e.error]||`Recognition error: ${e.error}`);rec.onend=()=>{if($("transcript").textContent!=="—")$("status").textContent="Recognition finished. Check the transcript."};rec.start()}
$("speak").onclick=hear;$("retry").onclick=hear;
document.querySelectorAll(".judge").forEach(b=>b.onclick=()=>{choice=b.dataset.v;document.querySelectorAll(".judge").forEach(x=>x.classList.remove("sel"));b.classList.add("sel");$("next").disabled=false});
$("next").onclick=()=>{R.push([i+1,T[i],$("transcript").textContent,choice,$("note").value.trim()]);if(i<T.length-1){i++;draw()}else finish()};
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function finish(){$("test").classList.add("hide");$("results").classList.remove("hide");let c={PASS:0,MINOR:0,FAIL:0};R.forEach(x=>c[x[3]]++);$("summary").textContent=`PASS: ${c.PASS} | MINOR ERROR: ${c.MINOR} | MEANING / CRITICAL ERROR: ${c.FAIL}`;$("tbody").innerHTML=R.map(x=>`<tr>${x.map(y=>`<td>${esc(y)}</td>`).join("")}</tr>`).join("")}
$("restart").onclick=()=>{i=0;R=[];$("results").classList.add("hide");$("test").classList.remove("hide");draw()};
$("export").onclick=()=>{let a=[["Test","Expected","Transcript","Result","Note"],...R],csv=a.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n"),blob=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}),l=document.createElement("a");l.href=URL.createObjectURL(blob);l.download="speak-test-round-a.csv";l.click();setTimeout(()=>URL.revokeObjectURL(l.href),1000)};
$("compat").textContent=SR?"✓ Speech-recognition interface detected. Allow microphone access when asked.":"⚠ Speech recognition is not exposed by this browser. LISTEN may work, but SPEAK cannot run.";draw();